version: "2"
services:
    mysql-app:
        image: mysql
        container_name: orange-mysql
        ports:
          - "3306:3306"
        volumes:
            - "./partials/mysql:/var/lib/mysql:rw"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_USER=db
            - MYSQL_PASSWORD=db
    php-app:
        build: "./php"
        container_name: orange-php
        volumes:
            - "/home/nico/Projects/:/var/www"
        links:
#            - elk-app
            - mysql-app
        hostname: "php-app"
    nginx-app:
        image: nginx:1.12
        container_name: orange-nginx
#        hostname: orange
#        domainname: orange.dev
#        tty: true
        ports:
           - "80:80"
        volumes:
            - "./partials/nginx:/etc/nginx/conf.d"
            - "/home/nico/Projects:/var/www"
        depends_on:
            - php-app
#    elk-app:
#        image: sebp/elk:540
#        ports:
#            - "5601:5601"
#            - "9200:9200"
#            - "5044:5044"
