version: "2"
services:
    mysql-app:
        image: mysql
        container_name: mysql
        ports:
          - "3306:3306"
        volumes:
            - "./mysql:/var/lib/mysql:rw"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_USER=db
            - MYSQL_PASSWORD=db
    php-app:
        build: "./php"
        image: nicoorfi/php
        container_name: php
        volumes:
            - "/home/${USER}/Projects/:/var/www"
            - "/etc/hosts:/etc/hosts"
        links:
            - mysql-app
        hostname: "php-app"
    nginx-app:
        image: nginx:1.12
        container_name: nginx
        ports:
           - "8000:80"
        volumes:
           - "/home/${USER}/Projects:/var/www"
           - "./nginx:/etc/nginx"
           - "/etc/hosts:/etc/hosts"
        depends_on:
            - php-app
