version: "2"
services:
  nginx-app:
    image: nginx:1.12
    ports:
       - "80:80"
    volumes:
          - "./partials/nginx:/etc/nginx/conf.d"
          - "./App:/var/www/app"
  php-app:
      image: php:7.0.20-fpm
#      volumes:
#        - "./etc/php/fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf"
#        - "./etc/php/php.ini:/usr/local/etc/php/php.ini"
#        - "./App:/var/www/app"
  mysql-app:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db
        - MYSQL_USER=db
        - MYSQL_PASSWORD=db